#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -a; source "${script_dir}/.env.local"; set +a

. dev/k8s-env

secret="$(kubectl get secret --namespace xmtp-system argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode)"
echo -n "${secret}" | pbcopy

echo "Password has been copied to your clipboard"
echo "Open http://argo.localhost/"
