#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -a; source "${script_dir}/.env.local"; set +a

plan="${PLAN}"
plan_dir="${script_dir}/plans/${plan}"

if [ ! -d "${plan_dir}" ]; then
    echo "${plan_dir} does not exist"
    exit 1
fi

destroy_path="${plan_dir}/destroy.sh"

if [ -f "${destroy_path}" ]; then
    cd "${plan_dir}"
    ./destroy.sh "$@"
else
    "${script_dir}"/tf destroy "$@"
fi
