#!/bin/bash

PLAN=$(source dev/.env.local; echo "$PLAN")
plan_dir="${PWD}/dev/plans/${PLAN}"

if [ -f "${plan_dir}"/update-kubeconfig.sh ]; then
    "${plan_dir}"/update-kubeconfig.sh
fi
export KUBECONFIG="${plan_dir}/.xmtp/kubeconfig.yaml"

alias k=kubectl
alias kn="kubectl -n xmtp-nodes"
alias ks="kubectl -n xmtp-system"
alias kt="kubectl -n xmtp-tools"
