#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -a; source "${script_dir}/.env.local"; set +a

plan_dir="${script_dir}/plans/${PLAN}"

function tf() {
    terraform -chdir="${plan_dir}" "$@"
}

tf "$@"
