#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -a; source "${script_dir}/.env.local"; set +a

plan_dir="${script_dir}/plans/${PLAN}"

if [ ! -d "${plan_dir}" ]; then
    echo "${plan_dir} does not exist"
    exit 1
fi

apply_path="${plan_dir}/apply.sh"

if [ -f "${apply_path}" ]; then
    cd "${plan_dir}"
    ./apply.sh
else
    "${script_dir}"/tf init -upgrade
    "${script_dir}"/tf apply -auto-approve
fi
