{
 "title": "XMTP Network API",
 "tags": [ "xmtpd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "grpc_method",
    "query": {
     "query": "label_values(xmtpd_api_request_duration_us_bucket, grpc_method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(xmtpd_api_request_duration_us_count{grpc_method=~\"$grpc_method\"}[$__rate_interval])) by (host_name, grpc_method, grpc_error_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API request durations",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (increase(xmtpd_api_request_duration_us_bucket{grpc_method=~\"$grpc_method\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API requests by node",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(xmtpd_api_request_duration_us_count{grpc_method=~\"$grpc_method\"}[$__rate_interval])) by(host_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}