{
 "title": "XMTP Cluster",
 "tags": [ "xmtpd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API requests per second by gRPC method",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(xmtpd_api_request_duration_us_count{}[$__rate_interval])) by (grpc_method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API error rate (current)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(xmtpd_api_request_duration_us_count{grpc_error_code!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API error percentage (over time period)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(xmtpd_api_request_duration_us_count{grpc_error_code!=\"\"}) / sum(xmtpd_api_request_duration_us_count{grpc_error_code=~\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API requests per second by XMTP node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(xmtpd_api_request_duration_us_count{}[$__rate_interval])) by (kube_app_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API requests per second by XMTP node and gRPC method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(xmtpd_api_request_duration_us_count{}[$__rate_interval])) by (kube_app_name, grpc_method)",
     "legendFormat": "{{kube_app_name}}/{{grpc_method}}"
    },
    {
     "expr": "sum(rate(xmtpd_api_request_duration_us_count{grpc_error_code!=\"\"}[$__rate_interval])) by (kube_app_name, grpc_method, grpc_error_code) != 0",
     "legendFormat": "{{kube_app_name}}/{{grpc_method}} {{grpc_error_code}}"
    }
   ]
  },
  {
   "title": "Publish API request durations by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(xmtpd_api_request_duration_us_bucket{grpc_method=\"Publish\"}[$__rate_interval])) by (le, kube_app_name))",
     "legendFormat": "{{kube_app_name}}/p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(xmtpd_api_request_duration_us_bucket{grpc_method=\"Publish\"}[$__rate_interval])) by (le, kube_app_name))",
     "legendFormat": "{{kube_app_name}}/p99"
    }
   ]
  },
  {
   "title": "Publish API request durations by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(xmtpd_api_request_duration_us_bucket{grpc_method=\"Publish\"}[$__rate_interval])) by (le, kube_app_name))",
     "legendFormat": "{{kube_app_name}}/p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(xmtpd_api_request_duration_us_bucket{grpc_method=\"Publish\"}[$__rate_interval])) by (le, kube_app_name))",
     "legendFormat": "{{kube_app_name}}/p99"
    }
   ]
  },
  { "title": "CRDT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CRDT received events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(xmtpd_crdt_received_events[$__rate_interval])) by (kube_app_name, action)",
     "legendFormat": "{{kube_app_name}}/{{action}}"
    }
   ]
  },
  {
   "title": "CRDT sync fetches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(xmtpd_sync_fetch_duration_us_count[$__rate_interval])) by (kube_app_name)",
     "legendFormat": "{{kube_app_name}}/{{action}}"
    }
   ]
  },
  {
   "title": "CRDT channel free space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(xmtpd_crdt_channel_free_space_bucket{}[$__rate_interval])) by (le, kube_app_name))",
     "legendFormat": "{{kube_app_name}}/p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(xmtpd_crdt_channel_free_space_bucket{}[$__rate_interval])) by (le, kube_app_name))",
     "legendFormat": "{{kube_app_name}}/p99"
    }
   ]
  },
  {
   "title": "CRDT sync fetch durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(xmtpd_sync_fetch_duration_us_bucket{}[$__rate_interval])) by (le, kube_app_name))",
     "legendFormat": "{{kube_app_name}}/p50"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(xmtpd_sync_fetch_duration_us_bucket{}[$__rate_interval])) by (le, kube_app_name))",
     "legendFormat": "{{kube_app_name}}/p99"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Container CPU usage (percent) by node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{namespace=\"xmtp-nodes\",container=\"node\"}[$__rate_interval])\n    ) by (pod)\n      /\n    sum(\n      kube_pod_container_resource_limits{namespace=\"xmtp-nodes\",container=\"node\",resource=\"cpu\"}\n    ) by (pod)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage (percent) by node",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      container_memory_usage_bytes{namespace=\"xmtp-nodes\",container=\"node\"}\n    ) by (pod)\n      /\n    sum(\n      kube_pod_container_resource_limits{namespace=\"xmtp-nodes\",container=\"node\",resource=\"memory\"}\n    ) by (pod)\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container CPU usage (ms) by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=\"xmtp-nodes\",container=\"node\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}/p50"
    }
   ]
  },
  {
   "title": "Container CPU usage (percent) by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{namespace=\"xmtp-nodes\",container=\"node\"}[$__rate_interval])\n    ) by (pod)\n      /\n    sum(\n      kube_pod_container_resource_limits{namespace=\"xmtp-nodes\",container=\"node\",resource=\"cpu\"}\n    ) by (pod)\n)",
     "legendFormat": "{{pod}}/p50"
    }
   ]
  },
  {
   "title": "Container memory usage (bytes) by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_usage_bytes{namespace=\"xmtp-nodes\",container=\"node\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage (percent) by node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      container_memory_usage_bytes{namespace=\"xmtp-nodes\",container=\"node\"}\n    ) by (pod)\n      /\n    sum(\n      kube_pod_container_resource_limits{namespace=\"xmtp-nodes\",container=\"node\",resource=\"memory\"}\n    ) by (pod)\n)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(increase(container_oom_events_total{namespace=\"xmtp-nodes\",container=\"node\"}[$__rate_interval])) by (pod) != 0",
     "legendFormat": "{{pod}}/OOM"
    }
   ]
  }
 ]
}