{
 "title": "CRDT Metrics",
 "tags": [ "xmtpd" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Received Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(xmtpd_crdt_received_events[$__rate_interval])) by (host_name, action)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Fetch Durations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(xmtpd_sync_fetch_duration_us_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Fetch Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(xmtpd_sync_fetch_duration_us_count[$__rate_interval])) by (host_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channel Free Space",
   "type": "heatmap",
   "description": "Samples of (cap(ch) - len(ch)) ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(xmtpd_crdt_channel_free_space_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}